In [1]:
#04_Numpy_06_20160508

In [2]:
import numpy as np #import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [4]:
%pylab

Using matplotlib backend: Qt4Agg
Populating the interactive namespace from numpy and matplotlib


In [5]:
#np.save() / np.load(), saving and loading array data on disk. file extension *.npy

In [6]:
arr=np.arange(10) 

In [7]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.save('0406_arr_1',arr) #叫用 numpy.save() , 存檔檔名--> 0406_arr_1.npy, 位置為工作目錄

In [9]:
np.load('0406_arr_1.npy') #以 numpy.load() 從hard disk 中讀取 array 資料

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# save multiple arrays in a zip archive using np.savez

In [11]:
arr2=np.arange(2,20,2)

In [12]:
arr2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
np.savez('array_archive',a=arr,b=arr2) #將arr, arr2 存入 arrar_archive_npz

In [14]:
arch1=np.load('array_archive.npz')

In [15]:
arch1['a'] #像字典一樣取出 arrar_archive_npz file 中第一組陣列

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arch1['b']

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
#Saving and Loading Text Files, np.loadtxt( ) 

In [18]:
#a simple case of a comma-separated file (CSV), array_ex.txt

In [19]:
!type array_ex.txt # 在liunx 用 !cat

0.580052,0.186730,1.040717,1.134411
0.194163,-0.636917,-0.938659,0.124094
-0.126410,0.268607,-0.695724,0.047428
-1.484413,0.004176,-0.744203,0.005487
2.302869,0.200131,1.670238,-1.881090
-0.193230,1.047233,0.482803,0.960334


In [20]:
arr03=np.loadtxt('array_ex.txt',delimiter=',') #numpy.loadtxt()

In [21]:
arr03 #轉為2維陣列

array([[ 0.580052,  0.18673 ,  1.040717,  1.134411],
       [ 0.194163, -0.636917, -0.938659,  0.124094],
       [-0.12641 ,  0.268607, -0.695724,  0.047428],
       [-1.484413,  0.004176, -0.744203,  0.005487],
       [ 2.302869,  0.200131,  1.670238, -1.88109 ],
       [-0.19323 ,  1.047233,  0.482803,  0.960334]])

In [23]:
arr04=np.random.randn(3,4) #使用 np.random.randn 產生一個常態分佈 3x4 陣列

In [24]:
arr04

array([[-1.58453857, -0.0949323 , -0.97293264, -0.79100345],
       [-1.3236527 ,  1.28087565, -0.05197143, -0.60198292],
       [-0.18258755,  0.52277267,  1.01528868,  0.88375291]])

In [25]:
np.savetxt('arr_test.txt',arr04,delimiter=',') #np.savetxt()

In [26]:
!type arr_test.txt

-1.584538565643397456e+00,-9.493230449134705540e-02,-9.729326382631162673e-01,-7.910034522957808401e-01
-1.323652696319694178e+00,1.280875650670285415e+00,-5.197143410830244031e-02,-6.019829166330709080e-01
-1.825875525247967479e-01,5.227726743477845162e-01,1.015288680059991622e+00,8.837529135117114798e-01
