In [1]:
#04_Numpy_03_20160429 

In [2]:
import numpy as np #import numpy as np

In [3]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe']) 
#an array of names with duplicates.

In [4]:
data=np.random.randn(7,4) #叫用 randn() 

In [5]:
data #常態分佈 7X4 array 

array([[-1.04202044,  0.03105891,  1.06997815,  0.11356389],
       [-0.47549999,  1.7522444 , -0.80789538, -0.63436608],
       [ 1.49043889, -0.10589923,  0.29475655,  0.73735657],
       [-1.17179066, -0.55896019, -0.91438157,  1.04605195],
       [-0.67261345,  0.16276835, -1.27605856,  0.70120073],
       [ 0.41189964, -0.16623855,  1.22226714, -2.49632658],
       [ 0.43002044,  1.38960144,  1.63176974,  0.27519551]])

In [6]:
names #1-dimensional array, 7個元素

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='<U4')

In [7]:
#布林運算 == , 1D boolean array

In [8]:
names=='Bob' #array names 中, =='Bob' --> True

array([ True, False, False,  True, False, False, False], dtype=bool)

In [10]:
data[names=='Bob'] #使用 names=='Bob' 布林運算結果 [ True, False, False,  True, False, False, False]
                   #作為 ndarray data 的slice
                   #結果是 data axis0 [0] [3] 

array([[-1.04202044,  0.03105891,  1.06997815,  0.11356389],
       [-1.17179066, -0.55896019, -0.91438157,  1.04605195]])

In [11]:
data[names=='Bob',2:] #將上一行結果, 再沿 axis1 切 [2:] 

array([[ 1.06997815,  0.11356389],
       [-0.91438157,  1.04605195]])

In [12]:
#布林運算 != ,(or -) 

In [13]:
names!='Bob' # 1D boolean array

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [14]:
data[names!='Bob'] 

array([[-0.47549999,  1.7522444 , -0.80789538, -0.63436608],
       [ 1.49043889, -0.10589923,  0.29475655,  0.73735657],
       [-0.67261345,  0.16276835, -1.27605856,  0.70120073],
       [ 0.41189964, -0.16623855,  1.22226714, -2.49632658],
       [ 0.43002044,  1.38960144,  1.63176974,  0.27519551]])

In [15]:
#布林運算 and (&), or(|) 

In [16]:
mask=(names=='Bob')|(names=='Will') 

In [17]:
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [18]:
data[mask]

array([[-1.04202044,  0.03105891,  1.06997815,  0.11356389],
       [ 1.49043889, -0.10589923,  0.29475655,  0.73735657],
       [-1.17179066, -0.55896019, -0.91438157,  1.04605195],
       [-0.67261345,  0.16276835, -1.27605856,  0.70120073]])

In [19]:
#布林運算 another example

In [20]:
data[data < 0] = 0 #將 ndarray object data 中負數值的元素皆設定為0

In [21]:
data

array([[ 0.        ,  0.03105891,  1.06997815,  0.11356389],
       [ 0.        ,  1.7522444 ,  0.        ,  0.        ],
       [ 1.49043889,  0.        ,  0.29475655,  0.73735657],
       [ 0.        ,  0.        ,  0.        ,  1.04605195],
       [ 0.        ,  0.16276835,  0.        ,  0.70120073],
       [ 0.41189964,  0.        ,  1.22226714,  0.        ],
       [ 0.43002044,  1.38960144,  1.63176974,  0.27519551]])

In [22]:
data[names != 'Joe']=7 #Setting whole rows or columns using a 1D boolean array

In [23]:
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.        ,  1.7522444 ,  0.        ,  0.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.41189964,  0.        ,  1.22226714,  0.        ],
       [ 0.43002044,  1.38960144,  1.63176974,  0.27519551]])

In [33]:
#Fancy Indexing

In [35]:
arr=np.empty((8,4)) # 8 × 4 array

In [39]:
for i in range(8):
    arr[i]=i+1

In [40]:
arr

array([[ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.]])

In [43]:
arr[[4,6,0]] #索引[4] [6] [0] 的子集,且以 4,6,0 為順序

array([[ 5.,  5.,  5.,  5.],
       [ 7.,  7.,  7.,  7.],
       [ 1.,  1.,  1.,  1.]])

In [45]:
arr[[-1,-3]] #倒數, -1為最後

array([[ 8.,  8.,  8.,  8.],
       [ 6.,  6.,  6.,  6.]])