In [1]:
#04_Numpy_05_20160508

In [2]:
import numpy as np #import numpy as np

In [3]:
from numpy.random import randn #from numpy.random import randn

In [4]:
import matplotlib.pyplot as plt #import matplotlib.pyplot as plt

In [5]:
%matplotlib inline

In [6]:
#Mathematical and Statistical Methods

In [7]:
#Aggregations (often called reductions) like sum, mean, and standard deviation std

In [8]:
arr=np.random.randn(5,4) #製作一組 normally-distributed data

In [9]:
arr #numpy.ndarray object

array([[ 1.40576806,  0.60541517,  0.94673884,  0.09469963],
       [-0.11649694, -0.04106679,  1.12607491, -0.92142958],
       [-0.54507579,  0.47690486,  0.11761088, -0.59496561],
       [ 1.42659866, -0.5678367 , -1.06960921,  0.5180088 ],
       [-0.43627296,  2.08519442,  0.50444702, -0.81700386]])

In [10]:
arr.mean() #叫用 mean() method  

0.2098851899656467

In [11]:
arr.sum() #叫用 sum() method

4.1977037993129338

In [12]:
arr.shape

(5, 4)

In [13]:
arr.mean(axis=0) #沿axis0 計算

array([ 0.34690421,  0.51172219,  0.32505249, -0.34413813])

In [14]:
arr.sum(1) #沿axis1 計算

array([ 3.0526217 ,  0.0470816 , -0.54552566,  0.30716156,  1.3363646 ])

In [15]:
#cumsum and cumprod do not aggregate

In [16]:
arr02=np.array([[0,1,2],[3,4,5],[6,7,8]])

In [17]:
arr02 #numpy.ndarray objecta

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
arr02.cumsum(0) #沿著 axis0 累加
                #    0,    1,    2
                #  0+3,  1+4,  2+5
                #0+3+6,1+4+7,2+5+8

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [19]:
arr02.cumprod(1) #沿著 axis1 
                 # 0, 0*1, 0*1*2
                 # 3, 3*4, 3*4*5
                 # 6, 6*7, 6*7*8

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

In [20]:
# Methods for Boolean Arrays

In [21]:
arr03=randn(100)

In [22]:
arr03

array([ 0.54665513, -0.72410648, -1.28394563, -0.3008683 , -0.63242565,
       -0.55219407,  1.2877984 , -1.35717933, -0.01738355, -0.4753172 ,
        1.89369944,  0.57207989,  2.31372138,  1.66226048,  0.19161508,
        0.4375482 , -1.55297621,  0.34653601,  0.37642058, -0.88787637,
        2.35808239,  0.26051455,  0.43091721, -0.47486801,  1.61370646,
        0.27140846, -1.59236896,  0.20396375,  1.36138757, -0.60010193,
       -1.13439287,  0.45069886, -0.16478636, -0.93409243, -1.41328922,
       -0.17778385, -1.48276565, -0.29580734, -0.2363087 ,  1.41788243,
        0.38681303,  1.28099031, -0.34824161,  0.63948581, -0.56512685,
        0.32702067,  0.17163924, -0.74938425,  0.89081971,  1.09745973,
        1.0088317 , -0.29332605, -0.7999299 ,  1.05315885,  0.12170105,
        0.26695518,  0.80131209,  0.32067873, -0.9073989 , -0.0201813 ,
        0.859068  ,  0.75643334,  0.02139729, -0.46886494,  0.60207411,
        0.2295929 , -1.30359248,  0.0349273 ,  1.83303907, -0.70

In [24]:
(arr03 > 0).sum() #arr03 中 正數的個數, 在這些方法中布林值會被強制轉換為1(True), 0(False) 
                  #sum() 用來計算 True 的個數

53

In [25]:
#any() and all()

In [26]:
bool_arr=np.array([False,False,True,False]) #create a bool array

In [27]:
bool_arr.any() #any(), 檢視 bool_arr 中是否有 True 值

True

In [28]:
arr04=np.array([4,5,7]) #numpy.ndarray object arr04 

In [29]:
arr04

array([4, 5, 7])

In [30]:
(arr04 > 5).any() #檢視 (arr04 > 5) 有無任一個 True

True

In [31]:
(arr04 > 5).all() #檢視 (arr04 > 5) 每一個是否皆為 True, 結果為 False

False

In [32]:
(arr04 > 3).all() #檢視 (arr04 > 5) 每一個是否皆為 True, 結果為 True

True

In [34]:
#練習:
#arr041=np.array([[120,-144,20],[390,-13,-90],[-490,89,130]])
#(arr041.sum(axis=1) > 0).all() 

In [33]:
#sorting

In [33]:
arr05=randn(8)

In [34]:
arr05

array([-0.27316483,  1.27613207, -1.11408063, -1.57396713,  0.34146587,
        0.29652747, -0.65683066,  0.09043367])

In [35]:
arr05.sort() #沒有copy, 就是 arr05 自身排序

In [36]:
arr05

array([-1.57396713, -1.11408063, -0.65683066, -0.27316483,  0.09043367,
        0.29652747,  0.34146587,  1.27613207])

In [37]:
#多維陣列,沿某一 axis 排序

In [38]:
arr06=randn(5,3)

In [39]:
arr06

array([[-1.2009874 ,  0.08850827,  0.24332165],
       [ 0.30025798,  0.66041628, -0.38547847],
       [-1.68972025, -0.55672062,  0.48360287],
       [-0.41605056, -0.71615916,  0.86003035],
       [-0.39175125,  0.70582012,  0.13813161]])

In [40]:
arr06.sort(0) #沿 axis0 sorting

In [41]:
arr06

array([[-1.68972025, -0.71615916, -0.38547847],
       [-1.2009874 , -0.55672062,  0.13813161],
       [-0.41605056,  0.08850827,  0.24332165],
       [-0.39175125,  0.66041628,  0.48360287],
       [ 0.30025798,  0.70582012,  0.86003035]])

In [42]:
arr06.sort(1) #沿 axis1 sorting

In [43]:
arr06

array([[-1.68972025, -0.71615916, -0.38547847],
       [-1.2009874 , -0.55672062,  0.13813161],
       [-0.41605056,  0.08850827,  0.24332165],
       [-0.39175125,  0.48360287,  0.66041628],
       [ 0.30025798,  0.70582012,  0.86003035]])

In [44]:
#利用 sort 及 slice 取前面 10%的資料

In [45]:
arr07=randn(100) 

In [46]:
arr07

array([ 1.91638473,  0.23994593,  0.15329653, -0.29629913, -1.18904552,
       -0.03992272, -0.67738844, -0.16635251, -2.10037506, -0.45951526,
        0.74971193, -0.48745147, -0.00746754, -0.07255009, -0.90356833,
        0.06291296,  0.17473576, -0.4899817 , -0.00900906,  0.4205378 ,
        0.18470658,  1.02867941,  0.12797024, -0.91767042,  0.1363749 ,
        0.97164813,  0.38395896,  0.84603163,  1.35728257, -1.65229928,
       -1.60168851, -0.27027453, -0.58193016,  1.58161214, -0.5926414 ,
       -1.76605129,  0.39870449,  0.31958789,  1.06269339, -1.30766491,
       -0.91206324,  0.32052875, -0.3912391 , -1.03220099,  0.44227307,
       -1.12033357,  1.46899038, -1.53282873,  0.98256737, -1.13125182,
        0.32670241,  0.26972285, -1.42766765, -1.15215368,  0.6792135 ,
       -0.47397515, -1.665165  , -0.1803816 , -0.78280541, -0.47425531,
        0.41891005, -1.91072157, -1.0663103 ,  0.92605252, -0.34765855,
        0.16334256,  1.53177651, -0.18676499,  0.01440156, -1.88

In [47]:
arr07.sort()

In [48]:
arr07

array([-2.24615266, -2.10037506, -1.91072157, -1.88429805, -1.76605129,
       -1.665165  , -1.65229928, -1.60168851, -1.53282873, -1.48494749,
       -1.42766765, -1.30766491, -1.18904552, -1.15215368, -1.13125182,
       -1.12033357, -1.0663103 , -1.06548608, -1.05670129, -1.03220099,
       -1.03220014, -0.9374375 , -0.91767042, -0.91206324, -0.90356833,
       -0.84224689, -0.83189965, -0.78280541, -0.67738844, -0.65210696,
       -0.5926414 , -0.58193016, -0.4899817 , -0.48745147, -0.47425531,
       -0.47397515, -0.45951526, -0.3912391 , -0.37126017, -0.34765855,
       -0.32224058, -0.31922388, -0.31721888, -0.29629913, -0.27027453,
       -0.18676499, -0.1803816 , -0.17944946, -0.16635251, -0.09016079,
       -0.07255009, -0.03992272, -0.03329268, -0.00900906, -0.00746754,
        0.01440156,  0.06291296,  0.07537365,  0.09293362,  0.12797024,
        0.1363749 ,  0.15329653,  0.16334256,  0.17473576,  0.18470658,
        0.23994593,  0.26972285,  0.31683764,  0.31958789,  0.32

In [49]:
arr07[0:int(0.1*len(arr07))] #將已排序的 arr07 切片 [0:int(0.1*len(arr07))] 

array([-2.24615266, -2.10037506, -1.91072157, -1.88429805, -1.76605129,
       -1.665165  , -1.65229928, -1.60168851, -1.53282873, -1.48494749])

In [50]:
#練習: 取最高的 5%

In [51]:
arr07[:-(int(0.05*len(arr07))+1):-1] 

array([ 1.91638473,  1.8786485 ,  1.79965196,  1.77766516,  1.6117195 ])

In [52]:
list01=[0,1,2,3,4,5]

In [53]:
list01[0:3]

[0, 1, 2]

In [54]:
list01[:-3:-1]

[5, 4]

In [55]:
# Unique and Other Set Logic, SQL unique

In [56]:
names=np.array(['Bob','Joe','Will','Bob','Joe','Joe']) #array object --> names

In [57]:
np.unique(names) #unique

array(['Bob', 'Joe', 'Will'], 
      dtype='<U4')

In [58]:
ints=np.array([3,3,4,2,5,3,1]) #array of ints

In [59]:
np.unique(ints)

array([1, 2, 3, 4, 5])

In [60]:
ints

array([3, 3, 4, 2, 5, 3, 1])

In [61]:
#與np.unique 等價的 Python --> sorted(set(names))

In [62]:
set(names)

{'Bob', 'Joe', 'Will'}

In [63]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [64]:
#np.in1d

In [65]:
values=np.array([6,0,0,3,2,5,6])

In [66]:
values

array([6, 0, 0, 3, 2, 5, 6])

In [67]:
np.in1d(values,[2,3,6])

array([ True, False, False,  True,  True, False,  True], dtype=bool)