In [1]:
#05_panda_05_20160812, Arithmetic and data alignment

In [2]:
from pandas import DataFrame,Series #from pandas import DataFrame,Series

In [3]:
import pandas as pd #慣例

In [4]:
import numpy as np #import numpy as np

In [5]:
import matplotlib.pyplot as plt #for plot

In [6]:
%matplotlib inline

In [7]:
#example 1:Series Object 相加

In [11]:
s1=Series([7.3,-2.4,3.0,9.2],index=['A','C','D','E'])

In [12]:
s2=Series([-2.3,4.5,8.8,-4.3,4.4],index=['A','C','E','F','G'])

In [13]:
s1 #Series s1

A    7.3
C   -2.4
D    3.0
E    9.2
dtype: float64

In [14]:
s2 #Series s2

A   -2.3
C    4.5
E    8.8
F   -4.3
G    4.4
dtype: float64

In [15]:
#將兩個 Series Object s1,s2 相加 s1+s2
#index 'D' (s1有s2沒有), 
#index 'E,F' (s2有s1沒有)
s1+s2

A     5.0
C     2.1
D     NaN
E    18.0
F     NaN
G     NaN
dtype: float64

In [19]:
#DataFrame:
#In the case of DataFrame, 
#alignment is performed on both the rows and the columns

In [16]:
df1=DataFrame(np.arange(1.0,10.0).reshape(3,3),
             columns=list('BCD'),
             index=[2014,2015,2016])

In [17]:
df2=DataFrame(np.arange(12.0).reshape(4,3),
             columns=list('BDE'),
             index=[2013,2014,2015,2016])

In [18]:
df1

B    C    D
2014  1.0  2.0  3.0
2015  4.0  5.0  6.0
2016  7.0  8.0  9.0

In [19]:
df2

B     D     E
2013  0.0   1.0   2.0
2014  3.0   4.0   5.0
2015  6.0   7.0   8.0
2016  9.0  10.0  11.0

In [20]:
df1+df2

B   C     D   E
2013   NaN NaN   NaN NaN
2014   4.0 NaN   7.0 NaN
2015  10.0 NaN  13.0 NaN
2016  16.0 NaN  19.0 NaN

In [21]:
#Arithmetic methods with fill values

In [22]:
df1 = DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))

In [23]:
df2 = DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))

In [24]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [25]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [26]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [27]:
df1.add(df2, fill_value=0)
#雙方缺的值以0取代

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [28]:
#Operations between DataFrame and Series

In [ ]:
#example 1: ndarray 間的算術運算
#           broadcasting

In [29]:
arr = np.arange(12.).reshape((3, 4))

In [31]:
arr #numpy.ndarray object arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [32]:
arr[0] #仍是一個 ndarray object

array([ 0.,  1.,  2.,  3.])

In [36]:
arr-arr[0] 

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [37]:
#example 2: Operations between a DataFrame

In [38]:
df01 = DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [39]:
df01 #DataFrame df01

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [40]:
s01=df01.ix[0] 
#以ix[0]擷取 'Utah' row
#成 Series s01

In [41]:
s01 #Series s01

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [42]:
df01-s01 #DataFrame - Series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [43]:
df01+2*s01 #DataFrame + Series

b     d     e
Utah    0.0   3.0   6.0
Ohio    3.0   6.0   9.0
Texas   6.0   9.0  12.0
Oregon  9.0  12.0  15.0

In [44]:
#example 3: 沿軸0 (axis=0) 運算

In [45]:
df01

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [46]:
s02=df01['d']

In [47]:
s02

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [48]:
df01.sub(s02,axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [49]:
df01.add(s02*2,axis=0)

b     d     e
Utah     2.0   3.0   4.0
Ohio    11.0  12.0  13.0
Texas   20.0  21.0  22.0
Oregon  29.0  30.0  31.0

In [50]:
#Function application and mapping

In [51]:
df5=DataFrame(np.random.randn(4,3),columns=['KHH','TPE','TNA'],
             index=[2014,2015,2016,2017])

In [52]:
df5 #Dataframe df5

KHH       TPE       TNA
2014  0.960263 -0.915417 -1.042425
2015 -0.730698  0.478912 -0.178442
2016  0.438836 -0.572314 -0.749660
2017  0.695892 -1.177198 -0.042903

In [53]:
#example 1: 將np.abs() 套用在 df5
np.abs(df5)

KHH       TPE       TNA
2014  0.960263  0.915417  1.042425
2015  0.730698  0.478912  0.178442
2016  0.438836  0.572314  0.749660
2017  0.695892  1.177198  0.042903

In [54]:
#example 2: Dataframe.apply() method

In [55]:
lf01= lambda x: x.max()-x.min()
#定義 lambda function lf01

In [56]:
df5.apply(lf01) #預設沿axis=0

KHH    1.690961
TPE    1.656110
TNA    0.999522
dtype: float64

In [57]:
df5.apply(lf01,axis=0)#指明axis=0

KHH    1.690961
TPE    1.656110
TNA    0.999522
dtype: float64

In [58]:
df5.apply(lf01,axis=1)#指明沿axis=1

2014    2.002688
2015    1.209610
2016    1.188496
2017    1.873089
dtype: float64

In [59]:
#example 3:apply 一般函數

In [60]:
def f2(x):     #定義function f2(), 傳回值為 Series
     return Series([x.min(), x.max()], index=['最小值', '最大值'])

In [61]:
df5.apply(f2)

KHH       TPE       TNA
最小值 -0.730698 -1.177198 -1.042425
最大值  0.960263  0.478912 -0.042903