In [1]:
#ch15_03_tensor_1D2D.ipynb

In [1]:
import tensorflow as tf

In [3]:
#step1. 建立一維張量(tensor) --> vector, tf.Variable([list])
ts_1D=tf.Variable([2,5,7,8])

In [5]:
with tf.Session() as sess:
    init=tf.global_variables_initializer()
    sess.run(init)
    x1D=sess.run(ts_1D)
    print(x1D)

[2 5 7 8]


In [7]:
#step1.1 查看 1D tensor 
print(x1D.shape)

(4,)


In [8]:
#step2. 建立二維張量(tensor) --> array, tf.Variable([[list]])
ts_2D=tf.Variable([[2,5,7,8]])

In [9]:
with tf.Session() as sess01:
    init=tf.global_variables_initializer()
    sess01.run(init)
    x2D=sess01.run(ts_2D)
    print(x2D)

[[2 5 7 8]]


In [10]:
print(x2D.shape) #二維資料 (1,4), 第一個維度只有1筆資料 1

(1, 4)


In [11]:
#step2.1 建立另一個二維張量(tensor) --> array, tf.Variable([[list1],[list2],...])
ts_2D2=tf.Variable([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [12]:
with tf.Session() as sess02:
    init=tf.global_variables_initializer()
    sess02.run(init)
    x2D2=sess02.run(ts_2D2)
    print(x2D2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
print(x2D2.shape)

(3, 4)


In [14]:
#step3. 矩陣基本運算

In [16]:
#step3.1 矩陣乘法, tf.matmul()
X=tf.Variable([[10.0,10.0,10.0,10.0]]) #(1,4) 2維矩陣
W=tf.Variable([[2.0,3.0,4.0],[5.0,6.0,7.0],[8.0,9.0,10.0],[-2.0,-5.0,-8.0]]) #(4,3) 2維矩陣
XW=tf.matmul(X,W)

with tf.Session() as sess02:
    init=tf.global_variables_initializer()
    sess02.run(init)
    print(sess02.run(XW))

[[130 130 130]]


In [17]:
print(XW.shape)

(1, 3)


In [3]:
#step3.2 矩陣加法, 線性方程式　y=X*W+b
b=tf.Variable([[0.5,0.4,0.3]])
XW=tf.Variable([[130.0,130.0,130.0]])
sum=XW+b
with tf.Session() as sess03:
    init=tf.global_variables_initializer()
    sess03.run(init)
    print('XW+b=')
    print(sess03.run(sum))

XW+b=
[[ 130.5         130.3999939   130.30000305]]


In [4]:
#step3.3 矩陣加法與乘法, X*W+b
X=tf.Variable([[10.0,10.0,10.0,10.0]]) #(1,4) 2維矩陣
W=tf.Variable([[2.0,3.0,4.0],[5.0,6.0,7.0],[8.0,9.0,10.0],[-2.0,-5.0,-8.0]]) #(4,3) 2維矩陣
b=tf.Variable([[0.5,0.4,0.3]])

y=tf.matmul(X,W)+b

with tf.Session() as sess04:
    init=tf.global_variables_initializer()
    sess04.run(init)
    print('X*W+b=')
    print(sess04.run(y))

X*W+b=
[[ 130.5         130.3999939   130.30000305]]
