In [1]:
#Numpy_05_20160503

In [2]:
import numpy as np #import numpy as np

In [3]:
from numpy.random import randn #from numpy.random import randn

In [4]:
import matplotlib.pyplot as plt #import matplotlib.pyplot as plt

In [5]:
%matplotlib inline

In [6]:
#Mathematical and Statistical Methods

In [7]:
#Aggregations (often called reductions) like sum, mean, and standard deviation std

In [8]:
arr=np.random.randn(5,4) #製作一組 normally-distributed data

In [9]:
arr #numpy.ndarray object

array([[-0.79102504, -0.27258824,  1.04899979, -0.77153198],
       [-0.03614726, -0.74499009,  0.34507797, -1.38525598],
       [-0.09718111, -0.28855451,  0.18235359, -1.85793314],
       [-0.72590253, -0.50842228,  0.46859756, -0.00644891],
       [-0.49410239,  2.81039333, -0.71108791,  0.59367336]])

In [10]:
arr.mean() #叫用 mean() method  

-0.16210378780447479

In [11]:
arr.sum() #叫用 sum() method

-3.2420757560894957

In [12]:
arr.shape

(5, 4)

In [13]:
arr.mean(axis=0) #沿axis0 計算

array([-0.42887167,  0.19916764,  0.2667882 , -0.68549933])

In [14]:
arr.sum(1) #沿axis1 計算

array([-0.78614546, -1.82131536, -2.06131517, -0.77217616,  2.19887639])

In [15]:
#cumsum and cumprod do not aggregate

In [20]:
arr02=np.array([[0,1,2],[3,4,5],[6,7,8]])

In [21]:
arr02 #numpy.ndarray objecta

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
arr02.cumsum(0) #沿著 axis0 累加
                #    0,    1,    2
                #  0+3,  1+4,  2+5
                #0+3+6,1+4+7,2+5+8

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [23]:
arr02.cumprod(1) #沿著 axis1 
                 # 0, 0*1, 0*1*2
                 # 3, 3*4, 3*4*5
                 # 6, 6*7, 6*7*8

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

In [24]:
# Methods for Boolean Arrays

In [31]:
arr03=randn(100)

In [32]:
arr03

array([-0.61053373,  0.7351839 ,  0.6255526 ,  0.48245728,  0.85430011,
       -0.00786675, -1.32722955,  0.50009546, -1.17755239,  1.98831965,
        0.84407651, -0.69144499, -0.2812578 ,  0.13542092,  1.01270824,
        0.23393042, -1.21415229, -0.42287179, -1.53234583, -1.31088868,
       -0.68475258,  1.3344198 , -0.06981633, -0.72387335,  0.9153071 ,
       -0.71779661,  0.45142475,  1.58377577, -0.20880034,  1.72840144,
       -0.93367024, -0.161056  , -0.55315027,  2.18761038, -1.38795587,
       -0.97572883, -1.4263993 ,  0.04568191, -1.05556066, -1.26582743,
       -0.16665796, -0.75502432, -0.10075119,  0.07165692,  0.16061818,
       -1.00425735,  0.42736206, -0.0604713 ,  2.48754448,  0.71042669,
        0.54937913,  0.18077802, -0.45603298, -1.71321751, -2.0293947 ,
        1.48958848,  1.38616354, -0.87877343,  1.04797569,  0.27205284,
       -1.51880063,  0.92824069,  0.39573754, -0.7338545 ,  0.45684683,
        1.08974995,  0.29560642, -1.72742901,  0.84958737,  1.43

In [33]:
(arr03 > 0).sum() #arr03 中 正數的個數, 在這些方法中布林值會被強制轉換為1(True), 0(False) 
                  #sum() 用來計算 True 的個數

54

In [37]:
#any() and all()

In [38]:
bool_arr=np.array([False,False,True,False]) #create a bool array

In [39]:
bool_arr.any() #any(), 檢視 bool_arr 中是否有 True 值

True

In [40]:
arr04=np.array([4,5,7]) #numpy.ndarray object arr04 

In [41]:
arr04

array([4, 5, 7])

In [42]:
(arr04 > 5).any() #檢視 (arr04 > 5) 有無任一個 True

True

In [43]:
(arr04 > 5).all() #檢視 (arr04 > 5) 每一個是否皆為 True, 結果為 False

False

In [44]:
(arr04 > 3).all() #檢視 (arr04 > 5) 每一個是否皆為 True, 結果為 True

True

In [46]:
#sorting

In [47]:
arr05=randn(8)

In [48]:
arr05

array([-0.61222407,  1.4647044 ,  0.69515955,  0.48125241, -0.14860503,
        1.02511507,  1.81115012,  0.92737158])

In [49]:
arr05.sort() #沒有copy, 就是 arr05 自身排序

In [50]:
arr05

array([-0.61222407, -0.14860503,  0.48125241,  0.69515955,  0.92737158,
        1.02511507,  1.4647044 ,  1.81115012])

In [51]:
#多維陣列,沿某一 axis 排序

In [52]:
arr06=randn(5,3)

In [53]:
arr06

array([[ 0.42789189,  2.47866906,  0.78075619],
       [ 0.82480986, -0.32310433,  0.89568545],
       [-1.9718076 ,  1.28359353, -0.98321018],
       [ 0.71362266,  0.09930162,  1.05430765],
       [ 0.67389732, -0.90783221, -1.28405991]])

In [54]:
arr06.sort(0) #沿 axis0 sorting

In [55]:
arr06

array([[-1.9718076 , -0.90783221, -1.28405991],
       [ 0.42789189, -0.32310433, -0.98321018],
       [ 0.67389732,  0.09930162,  0.78075619],
       [ 0.71362266,  1.28359353,  0.89568545],
       [ 0.82480986,  2.47866906,  1.05430765]])

In [56]:
arr06.sort(1) #沿 axis1 sorting

In [57]:
arr06

array([[-1.9718076 , -1.28405991, -0.90783221],
       [-0.98321018, -0.32310433,  0.42789189],
       [ 0.09930162,  0.67389732,  0.78075619],
       [ 0.71362266,  0.89568545,  1.28359353],
       [ 0.82480986,  1.05430765,  2.47866906]])

In [58]:
#利用 sort 及 slice 取前面 10%的資料

In [59]:
arr07=randn(100) 

In [60]:
arr07

array([ 0.80450762, -1.92966076,  0.00959612,  0.28097258,  1.35744092,
        1.24779844, -1.38562586,  0.17895053,  0.55126891,  0.88507785,
       -0.08632661,  0.05389666,  2.68964848, -0.99469101, -0.37808665,
        1.66146778, -0.45643725,  0.70745065,  0.6902141 ,  1.1884371 ,
        0.89772821,  0.83368763,  1.37346358,  0.84849148,  0.20099398,
       -0.11206999, -0.24184335, -0.13858119,  0.41477979,  0.98371757,
        0.46393438, -0.42618562, -1.06738587,  0.00740003, -0.91210229,
        0.04475298, -0.24193125,  1.34414741, -0.09327293,  0.63272755,
       -0.37465029,  0.16407043,  0.32379922, -0.63164153, -0.41494326,
       -0.06921142,  0.41538754,  0.71796652,  0.47327543,  0.81668067,
        1.85776832,  0.65037015,  0.0819872 ,  1.25086176,  0.02246477,
        0.69180002,  0.06361096,  0.15628901,  1.55386197, -0.40571967,
       -0.96357461, -0.69221138, -1.66070418,  0.64435561,  0.03788071,
       -1.1534107 , -0.91382243,  1.23742528,  1.56203212, -1.48

In [61]:
arr07.sort()

In [62]:
arr07

array([-1.92966076, -1.92366043, -1.87823831, -1.66070418, -1.48964813,
       -1.38562586, -1.1534107 , -1.07347804, -1.06738587, -0.99469101,
       -0.96357461, -0.91382243, -0.91210229, -0.80451293, -0.69221138,
       -0.69162469, -0.63164153, -0.50946579, -0.45643725, -0.43335434,
       -0.42618562, -0.41494326, -0.40571967, -0.37808665, -0.37465029,
       -0.30042026, -0.28843244, -0.24193125, -0.24184335, -0.23236461,
       -0.22900176, -0.13858119, -0.11206999, -0.10538875, -0.09327293,
       -0.08632661, -0.07791894, -0.06921142, -0.01533023,  0.00740003,
        0.00959612,  0.01412109,  0.02246477,  0.02982251,  0.03788071,
        0.04475298,  0.05389666,  0.06361096,  0.0802983 ,  0.0819872 ,
        0.14018147,  0.15628901,  0.16407043,  0.17895053,  0.20099398,
        0.24926183,  0.25507088,  0.28097258,  0.32379922,  0.33953834,
        0.41477979,  0.41538754,  0.4199452 ,  0.43881428,  0.46393438,
        0.47327543,  0.51380205,  0.55126891,  0.63272755,  0.64

In [63]:
arr07[0:int(0.1*len(arr07))] #將已排序的 arr07 切片 [0:int(0.1*len(arr07))] 

array([-1.92966076, -1.92366043, -1.87823831, -1.66070418, -1.48964813,
       -1.38562586, -1.1534107 , -1.07347804, -1.06738587, -0.99469101])

In [65]:
#練習: 取最高的 5%

In [72]:
arr07[:-(int(0.05*len(arr07))+1):-1] 

array([ 2.68964848,  1.85776832,  1.66146778,  1.56203212,  1.55386197])

In [66]:
list01=[0,1,2,3,4,5]

In [67]:
list01[0:3]

[0, 1, 2]

In [70]:
list01[:-3:-1]

[5, 4]