In [2]:
#Numpy_02_20160427

In [1]:
import numpy as np #import numpy as np

In [3]:
#Operations between Arrays and Scalars, vectorization

In [4]:
ar1=np.array([[1,2,3],[4,5,6]],dtype=np.float64)

In [5]:
ar2=np.array([list(range(1,4)),list(range(4,7))]) 

In [6]:
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
ar1

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [8]:
ar1*ar2 #陣列運算, 陣列相乘

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [9]:
ar1+ar2 #陣列運算, 陣列相加

array([[  2.,   4.,   6.],
       [  8.,  10.,  12.]])

In [10]:
1/ar1 # 

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [11]:
ar2**0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])