In [2]:
import numpy as np
np.random.seed(0)#指定一個種子值確保每次執行時均產生同樣的亂數內容
#Numpy限制所有在陣列中的內容須為同樣的型態,如果不符會試著自動轉換
#https://github.com/jakevdp/PythonDataScienceHandbook/tree/master/notebooks

In [3]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [4]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [5]:
#需要明確的設定資料型態可以使用dtype
np.array([1, 2, 3, 4], dtype='float32')#bool_ int_ int8 int16,32,64 uint8,16,32,64(無號整數例如0~255) float_ float16,32,64

array([1., 2., 3., 4.], dtype=float32)

In [6]:
#Numpy陣列的屬性
#nested list導致多維數組
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [7]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # 一維 array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [8]:
print("x3 ndim: ", x3.ndim)#維度的數量
print("x3 shape:", x3.shape)#每一個維度的大小
print("x3 size: ", x3.size)#整個陣列的總大小

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [9]:
print("dtype:", x3.dtype)#陣列資料型態

dtype: int64


In [10]:
print("itemsize:", x3.itemsize, "bytes")#陣列中元素的大小(byte為單位)
print("nbytes:", x3.nbytes, "bytes")#列出整個陣列的大小(byte為單位)3*4*5*8=480

itemsize: 8 bytes
nbytes: 480 bytes


In [11]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [12]:
#多維子陣列的切片
x2[:2, :3] #2列3欄

array([[3, 5, 2],
       [7, 6, 8]])

In [13]:
x2[:3, ::2] #所有列的偶數欄

array([[3, 2],
       [7, 8],
       [1, 7]])

In [14]:
x2[::-1, ::-1]#子陣列各維度一起反轉

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [16]:
#存取陣列的列和欄
print(x2[:, 0])#第一欄
print(x2[0, :])#第一列 也可以是print(x2[0])
print(x2[0])

[3 7 1]
[3 5 2 4]
[3 5 2 4]


In [17]:
#陣列的複製
x2_sub_copy = x2[:2, :2].copy()#不會更改到原陣列的值:2, :2表示2*2的子陣列
print(x2_sub_copy)

[[3 5]
 [7 6]]


In [18]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)
print(x2)

[[42  5]
 [ 7  6]]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [19]:
#陣列的重塑Reshaping of Arrays
grid = np.arange(1, 10).reshape((3, 3))#要注意原來的陣列和重塑後的尺寸要能夠符合
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
x = np.array([1, 2, 3])
# row vector via reshape
x.reshape((1, 3))#建立列向量

array([[1, 2, 3]])

In [21]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [22]:
a = np.arange(6).reshape((3, 2))#3欄2列
print(a)

[[0 1]
 [2 3]
 [4 5]]


In [23]:
x.reshape((3, 1))#建立欄向量

array([[1],
       [2],
       [3]])

In [24]:
#陣列的串接和分割 np.concatenate np.vstack np.hstack
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])#np.concatenate使用一個陣列的tuple or list 當做第一個參數

array([1, 2, 3, 3, 2, 1])

In [25]:
#一次串接兩個以上
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [26]:
#使用在二維陣列上
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [27]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [29]:
#沿著第一軸串接
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [30]:
#沿著第二軸串接
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [31]:
#不同維度的串接np.vstack垂直堆疊 np.hstack水平堆疊
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [32]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [33]:
#分割陣列np.split np.hsplit np.vsplit
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])#[3, 5]索引位置
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [34]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]]


In [37]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
