In [1]:
#從無到有建立
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
type(L[0])

int

In [3]:
L2 = [str(c) for c in L]#建立一個字串形態的list
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [4]:
type(L2[0])

str

In [6]:
import numpy as np
np.zeros(10, dtype=int)#內容全為0長度為10的陣列

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones((3, 5), dtype=float)#內容全為1,3*5 array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)#填滿

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [10]:
# Create an array filled with a linear sequence依序填滿
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
# Create an array 5 個值的陣列在0到1之間平均分佈
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.69791852, 0.8615315 , 0.49592301],
       [0.34068369, 0.9757557 , 0.83247935],
       [0.80574499, 0.53463325, 0.1242426 ]])

In [14]:
# Create a 3x3 array 內容為常態分佈的亂數
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.62465872, -0.02926199, -0.99146611],
       [-0.59304523,  0.17071669, -1.38252114],
       [-0.60747095,  0.53250701,  0.61236032]])

In [15]:
# Create a 3x3 matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])