In [1]:
#結構化陣列
import numpy as np

想像一下，我們有很多人的數據類別（比如姓名，年齡和體重），我們希望存儲這些值以便在Python程序中使用。可以將它們存儲在三個獨立的數組中：

In [2]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

但這有點笨拙。這裡沒有任何東西告訴我們三個陣列是相關的;如果我們可以使用單一結構來存儲所有這些數據，那將更自然。 NumPy可以通過結構化數組處理這個問題，結構化數組是具有復合數據類型的數組。

回想一下，之前我們使用如下表達式創建了一個簡單的數組：

In [3]:
x = np.zeros(4, dtype=int)
print(x)

[0 0 0 0]


In [4]:
# 對結構化數組使用複合數據類型
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


這裡'U10'轉換為“最大長度為10的Unicode字符串”，“i4”轉換為“4字節（即32位）整數”，“f8”轉換為“8字節（即64位）浮點數“。我們將在下一節中討論這些類型代碼的其他選項。

現在我們已經創建了一個空容器數組，我們可以使用我們的值列表填充數組：

In [5]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [6]:
# Get all names
data['name']

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [7]:
# Get first row of data
data[0]

('Alice', 25, 55.)

In [8]:
# Get names where age is under 30
data[data['age'] < 30]['name']

array(['Alice', 'Doug'], dtype='<U10')

創建結構化數組
可以通過多種方式指定結構化數組數據類型。之前，我們看過字典方法：

In [9]:
np.dtype({'names':('name', 'age', 'weight'),
          'formats':('U10', 'i4', 'f8')})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [10]:
np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [11]:
np.dtype('S10,i4,f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])


Character	Description     	    Example
'b'      	Byte            	    np.dtype('b')
'i'      	Signed integer  	    np.dtype('i4') == np.int32
'u'      	Unsigned integer	    np.dtype('u1') == np.uint8
'f'      	Floating point	        np.dtype('f8') == np.int64
'c'	        Complex floating point	np.dtype('c16') == np.complex128
'S', 'a'	String	                np.dtype('S5')
'U'	        Unicode string	        np.dtype('U') == np.str_
'V'	        Raw data (void)	        np.dtype('V') == np.void

Character	Description	                  Example
'b'	        Byte	                      np.dtype('b')
'i'	        Signed integer	              np.dtype('i4') == np.int32
'u'	        Unsigned integer	          np.dtype('u1') == np.uint8
'f'	        Floating point	              np.dtype('f8') == np.int64
'c'	        Complex floating point	      np.dtype('c16') == np.complex128
'S', 'a'	String	                      np.dtype('S5')
'U'	        Unicode string	              np.dtype('U') == np.str_
'V'	        Raw data (void)	              np.dtype('V') == np.void

In [12]:
tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3, 3))])
X = np.zeros(1, dtype=tp)
print(X[0])
print(X['mat'][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
data['age']

array([25, 45, 37, 19], dtype=int32)