In [1]:
import numpy as np
import pandas as pd

In [2]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [3]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [4]:
x[x < 5]

array([0, 3, 3, 3, 2, 4])

In [6]:
np.sum(x < 5 , axis = 1)

array([3, 1, 2])

In [7]:
np.any(x > 8)

True

In [9]:
np.all(x > 8)

False

In [10]:
rainfall = pd.read_csv('data/Seattle2014.csv')['PRCP'].values
inches = rainfall / 254.0  # 1/10mm -> inches
inches.shape

(365,)

In [11]:
print("沒有下雨的天數:      ", np.sum(inches == 0))
print("下雨的天數:         ", np.sum(inches != 0))
print("雨量超過 0.5 inches 的天數:", np.sum(inches > 0.5))
print("雨量小於 < 0.2 inches 的天數 :", np.sum((inches > 0) &
                                                (inches < 0.2)))

沒有下雨的天數:       215
下雨的天數:          150
雨量超過 0.5 inches 的天數: 37
雨量小於 < 0.2 inches 的天數 : 75


In [12]:
# 對於所有的雨天資料建立一個遮罩
rainy = (inches > 0)

# 建立一個所有的夏天(6/21是第172天)的遮罩
days = np.arange(365)
summer = (days > 172) & (days < 262)

print("2014年下雨天的雨量中位數 (inches):   ",
      np.median(inches[rainy]))
print("2014年夏天降雨量的中位數 (inches):  ",
      np.median(inches[summer]))
print("2014年最大降雨量 2014 (inches): ",
      np.max(inches[summer]))
print("2014年非夏天降雨量的中位數 (inches):",
      np.median(inches[rainy & ~summer]))

2014年下雨天的雨量中位數 (inches):    0.19488188976377951
2014年夏天降雨量的中位數 (inches):   0.0
2014年最大降雨量 2014 (inches):  0.8503937007874016
2014年非夏天降雨量的中位數 (inches): 0.20078740157480315
