In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [3]:
s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

Series包含了一系列值和一系列索引，我們可以使用values和index屬性來訪問它們。

In [5]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [6]:
s.values

array([ 1.,  3.,  5., nan,  6.,  8.])

In [7]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [9]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [10]:
data['b']

0.5

In [11]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)#Series是對應型態鍵和一組型態值的結構
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [12]:
population['California']

38332521

In [13]:
population['California':'Florida']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

In [14]:
#例如，數據可以是列表或NumPy數組，在這種情況下，索引默認為整數序列：
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [15]:
#數據可以是純量，會被重複的填充到指定的索引：
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [16]:
#data可以是字典，其中index默認為已排序的字典鍵：
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [17]:
#在每種情況下，如果首選不同的結果，則可以顯式設置索引：
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

In [18]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [19]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [20]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [21]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [22]:
df2=pd.DataFrame({'A':1.,
                'B':pd.Timestamp('20170101'),
                'C':pd.Series(1, index=list(range(4)),dtype='float32'),
                'D':np.array([3]*4, dtype='int32'),
                'E':pd.Categorical(["test","train","test","train"]),
                'F':'foo'})
print(df2)

     A          B    C  D      E    F
0  1.0 2017-01-01  1.0  3   test  foo
1  1.0 2017-01-01  1.0  3  train  foo
2  1.0 2017-01-01  1.0  3   test  foo
3  1.0 2017-01-01  1.0  3  train  foo


In [24]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [25]:
df2.index

Int64Index([0, 1, 2, 3], dtype='int64')

In [27]:
df2.columns

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

In [28]:
df2.values

array([[1.0, Timestamp('2017-01-01 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2017-01-01 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2017-01-01 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2017-01-01 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [29]:
df2.T

0                    1                    2  \
A                    1                    1                    1   
B  2017-01-01 00:00:00  2017-01-01 00:00:00  2017-01-01 00:00:00   
C                    1                    1                    1   
D                    3                    3                    3   
E                 test                train                 test   
F                  foo                  foo                  foo   

                     3  
A                    1  
B  2017-01-01 00:00:00  
C                    1  
D                    3  
E                train  
F                  foo

In [30]:
# 排序，對於 axis=1 以 row 方向排序 ascending=False 倒排序
print(df2.sort_index(axis=1, ascending=False))

     F      E  D    C          B    A
0  foo   test  3  1.0 2017-01-01  1.0
1  foo  train  3  1.0 2017-01-01  1.0
2  foo   test  3  1.0 2017-01-01  1.0
3  foo  train  3  1.0 2017-01-01  1.0


In [31]:
# 排序，對於 axis=0 以 col 方向反向排序 (ascending=Fals 指定排序方式)
print(df2.sort_index(axis=0, ascending=False))

     A          B    C  D      E    F
3  1.0 2017-01-01  1.0  3  train  foo
2  1.0 2017-01-01  1.0  3   test  foo
1  1.0 2017-01-01  1.0  3  train  foo
0  1.0 2017-01-01  1.0  3   test  foo


In [32]:
# 排序 sort_values 針對單行的值進行排序
print(df2.sort_values(by='E'))

     A          B    C  D      E    F
0  1.0 2017-01-01  1.0  3   test  foo
2  1.0 2017-01-01  1.0  3   test  foo
1  1.0 2017-01-01  1.0  3  train  foo
3  1.0 2017-01-01  1.0  3  train  foo


In [34]:
from pandas_datareader import data as web

In [35]:
all_data={} #create a new dict object and named it all_data

In [36]:
for ticker in ['AAPL','IBM','MSFT','GOOG']: 
    all_data[ticker]=web.get_data_yahoo(ticker,'1/1/2010','1/1/2017')

In [37]:
all_data #dict object, key:value (value 資料型別為 DataFrame)

{'AAPL':                   High         Low        Open       Close       Volume  \
 Date                                                                      
 2009-12-31   30.478571   30.080000   30.447144   30.104286   88102700.0   
 2010-01-04   30.642857   30.340000   30.490000   30.572857  123432400.0   
 2010-01-05   30.798571   30.464285   30.657143   30.625713  150476200.0   
 2010-01-06   30.747143   30.107143   30.625713   30.138571  138040000.0   
 2010-01-07   30.285715   29.864286   30.250000   30.082857  119282800.0   
 2010-01-08   30.285715   29.865715   30.042856   30.282858  111902700.0   
 2010-01-11   30.428572   29.778572   30.400000   30.015715  115557400.0   
 2010-01-12   29.967142   29.488571   29.884285   29.674286  148614900.0   
 2010-01-13   30.132856   29.157143   29.695715   30.092857  151473000.0   
 2010-01-14   30.065714   29.860001   30.015715   29.918571  108223500.0   
 2010-01-15   30.228571   29.410000   30.132856   29.418571  148516900.0   
 201

In [38]:
all_data['AAPL']

High         Low        Open       Close       Volume  \
Date                                                                      
2009-12-31   30.478571   30.080000   30.447144   30.104286   88102700.0   
2010-01-04   30.642857   30.340000   30.490000   30.572857  123432400.0   
2010-01-05   30.798571   30.464285   30.657143   30.625713  150476200.0   
2010-01-06   30.747143   30.107143   30.625713   30.138571  138040000.0   
2010-01-07   30.285715   29.864286   30.250000   30.082857  119282800.0   
2010-01-08   30.285715   29.865715   30.042856   30.282858  111902700.0   
2010-01-11   30.428572   29.778572   30.400000   30.015715  115557400.0   
2010-01-12   29.967142   29.488571   29.884285   29.674286  148614900.0   
2010-01-13   30.132856   29.157143   29.695715   30.092857  151473000.0   
2010-01-14   30.065714   29.860001   30.015715   29.918571  108223500.0   
2010-01-15   30.228571   29.410000   30.132856   29.418571  148516900.0   
2010-01-19   30.741428   29.605715   29.761429   30.719999  182501900.0   
2010-01-20   30.792856   29.928572   30.701429   30.247143  153038200.0   
2010-01-21   30.472857   29.601429   30.297142   29.724285  152038600.0   
2010-01-22   29.642857   28.165714   29.540001   28.250000  220441900.0   
2010-01-25   29.242857   28.598572   28.930000   29.010000  266424900.0   
2010-01-26   30.530001   28.940001   29.421429   29.420000  466777500.0   
2010-01-27   30.082857   28.504286   29.549999   29.697144  430642100.0   
2010-01-28   29.357143   28.385714   29.275715   28.469999  293375600.0   
2010-01-29   28.885714   27.178572   28.725714   27.437143  311488100.0   
2010-02-01   28.000000   27.328571   27.481428   27.818571  187469100.0   
2010-02-02   28.045713   27.625713   27.987143   27.980000  174585600.0   
2010-02-03   28.600000   27.774286   27.881428   28.461428  153832000.0   
2010-02-04   28.338572   27.367144   28.104286   27.435715  189413000.0   
2010-02-05   28.000000   27.264286   27.518572   27.922857  212576700.0   
2010-02-08   28.268572   27.714285   27.955715   27.731428  119567700.0   
2010-02-09   28.214285   27.821428   28.059999   28.027143  158221700.0   
2010-02-10   28.085714   27.751429   27.984285   27.874287   92590400.0   
2010-02-11   28.535715   27.722857   27.840000   28.381428  137586400.0   
2010-02-12   28.805714   27.928572   28.301428   28.625713  163867200.0   
...                ...         ...         ...         ...          ...   
2016-11-17  110.349998  108.830002  109.809998  109.949997   27632000.0   
2016-11-18  110.540001  109.660004  109.720001  110.059998   28428900.0   
2016-11-21  111.989998  110.010002  110.120003  111.730003   29264600.0   
2016-11-22  112.419998  111.400002  111.949997  111.800003   25965500.0   
2016-11-23  111.510002  110.330002  111.360001  111.230003   27426400.0   
2016-11-25  111.870003  110.949997  111.129997  111.790001   11475900.0   
2016-11-28  112.470001  111.389999  111.430000  111.570000   27194000.0   
2016-11-29  112.029999  110.070000  110.779999  111.459999   28528800.0   
2016-11-30  112.199997  110.269997  111.599998  110.519997   36162300.0   
2016-12-01  110.940002  109.029999  110.370003  109.489998   37086900.0   
2016-12-02  110.089996  108.849998  109.169998  109.900002   26528000.0   
2016-12-05  110.029999  108.250000  110.000000  109.110001   34324500.0   
2016-12-06  110.360001  109.190002  109.500000  109.949997   26195500.0   
2016-12-07  111.190002  109.160004  109.260002  111.029999   29998700.0   
2016-12-08  112.430000  110.599998  110.860001  112.120003   27068300.0   
2016-12-09  114.699997  112.309998  112.309998  113.949997   34402600.0   
2016-12-12  115.000000  112.489998  113.290001  113.300003   26374400.0   
2016-12-13  115.919998  113.750000  113.839996  115.190002   43733800.0   
2016-12-14  116.199997  114.980003  115.040001  115.190002   34031800.0   
2016-12-15  116.730003  115.230003  115.379997  115.820000   46524500.0   
2016-12-16  116.500000  115.650002  116.470

In [39]:
all_data['GOOG']

High         Low        Open       Close      Volume  \
Date                                                                     
2009-12-31  310.679321  307.986847  310.356445  307.986847   2455400.0   
2010-01-04  312.721039  310.103088  311.449310  311.349976   3937800.0   
2010-01-05  311.891449  308.761810  311.563568  309.978882   6048500.0   
2010-01-06  310.907837  301.220856  310.907837  302.164703   8009000.0   
2010-01-07  303.029083  294.410156  302.731018  295.130463  12912000.0   
2010-01-08  299.675903  292.651581  294.087250  299.064880   9509900.0   
2010-01-11  300.276978  295.100647  300.276978  298.612823  14519600.0   
2010-01-12  297.147339  292.100159  296.893982  293.332153   9769600.0   
2010-01-13  292.288940  285.095734  286.382355  291.648102  13077600.0   
2010-01-14  295.180145  289.521942  290.063416  293.019196   8535300.0   
2010-01-15  294.862213  287.152344  294.752930  288.126007  10939600.0   
2010-01-19  293.302338  286.283020  288.722137  291.911407   8689500.0   
2010-01-20  291.096710  285.786224  291.096710  288.329681   6543600.0   
2010-01-21  291.513977  284.276062  289.834900  289.606384  12697400.0   
2010-01-22  283.456390  265.701874  280.426086  273.227905  13689200.0   
2010-01-25  273.163330  266.024780  271.528961  268.255249   8897200.0   
2010-01-26  273.024231  266.412231  267.246826  269.457428   8767600.0   
2010-01-27  272.055542  265.925415  268.886169  269.298462   7980200.0   
2010-01-28  271.732635  263.585632  270.485748  265.418701   6500100.0   
2010-01-29  268.747070  261.106750  267.505127  263.257751   8334700.0   
2010-02-01  266.173798  263.436584  265.572693  264.787811   4530800.0   
2010-02-02  265.751556  262.100281  265.751556  263.843964   8245600.0   
2010-02-03  269.298462  262.408295  262.626862  268.662598   6037000.0   
2010-02-04  267.261719  261.081909  266.764954  261.687958   6799200.0   
2010-02-05  265.026245  259.541931  262.492737  263.928406   6353000.0   
2010-02-08  269.248810  264.047638  264.529480  265.011353   5423500.0   
2010-02-09  269.015320  265.806183  268.026733  266.486755   5675700.0   
2010-02-10  267.157410  262.140045  265.309418  265.498199   5383700.0   
2010-02-11  268.498688  263.039185  264.936829  266.466888   4851300.0   
2010-02-12  266.839478  263.535950  264.762970  264.837494   4589000.0   
...                ...         ...         ...         ...         ...   
2016-11-17  772.700012  764.229980  766.919983  771.229980   1304000.0   
2016-11-18  775.000000  760.000000  771.369995  760.539978   1547100.0   
2016-11-21  769.700012  760.599976  762.609985  769.200012   1330600.0   
2016-11-22  776.960022  767.000000  772.630005  768.270020   1593100.0   
2016-11-23  768.283020  755.250000  767.729980  760.989990   1477400.0   
2016-11-25  765.000000  760.520020  764.260010  761.679993    587400.0   
2016-11-28  779.530029  759.799988  760.000000  768.239990   2188200.0   
2016-11-29  778.500000  768.239990  771.530029  770.840027   1616600.0   
2016-11-30  772.989990  754.830017  770.070007  758.039978   2392900.0   
2016-12-01  759.849976  737.025024  757.440002  747.919983   3017900.0   
2016-12-02  754.000000  743.099976  744.590027  750.500000   1452500.0   
2016-12-05  763.900024  752.900024  757.710022  762.520020   1394200.0   
2016-12-06  768.830017  757.340027  764.729980  759.109985   1690700.0   
2016-12-07  771.359985  755.799988  761.000000  771.190002   1761000.0   
2016-12-08  778.179993  767.229980  772.479980  776.419983   1488100.0   
2016-12-09  789.429993  779.020996  780.000000  789.289978   1821900.0   
2016-12-12  791.250000  784.354980  785.039978  789.270020   2104100.0   
2016-12-13  804.380005  793.340027  793.900024  796.099976   2145200.0   
2016-12-14  804.000000  794.010010  797.400024  797.070007   1704200.0   
2016-12-15  803.000000  792.919983  797.340027  797.849976   1626500.0   
2016-12-16  800.856018  790.289978  800.400024  790.799988   2428300.0   
2016-12-19  797.659973